### PR TITLE
feat: arc api mode implementation

### PR DESCRIPTION
**Pull request by wregulski**

### CODE REVIEW

**Comment by mrz1836** [comment]
@wregulski few more linter errors/issues

**Comment by wregulski** [comment]
> @wregulski few more linter errors/issues

@mrz1836 - I temporarily removed this unused code as it's referring to two test cases that needs to be adjusted.
I will take care of that in my first free slot.

**Comment by mrz1836** [comment]
Looks good @wregulski 

However I am going to need to create ` v2` of Minercraft and merge this in there... I'll keep you posted.

**Review by mrz1836 — APPROVED** [review]
LGTM - going to make a v2

**Pull request merged**
